### ISSUE TITLE
Error: no matches for kind "Scv" in version "core.run-linux.com/v1"

### ISSUE THREAD

**Issue by wenxinax** [NJUPT-ISL/Yoda-Scheduler#6]
Hi, the yoda-scheduler cannot work correctly in my environment. The scheduler container logs "Error: no matches for kind "Scv" in version "core.run-linux.com/v1"", but I didn't see any apiextensions definition in yoda-scheduler and scv deploy files. Are some installation steps missing?

**Comment by Mr-Linus** [comment]
Hi, it seems that you need to deploy the scv first. You can see the [SCV Get Started](https://github.com/NJUPT-ISL/SCV#get-started) to deploy the scv in order to collect the each NVIDIA GPU infomation.

**Comment by Mr-Linus** [comment]
@wenxinax  For more, you can join our qq group *1048469440* to talk about the usage of the yoda scheduler.
😺
